sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - cmake-data
      - g++-7


before_install:
  - git clone https://github.com/Grauniad/CMakeUtils.git
  - ./buildDeps.sh

install:
  - export CXX="g++-7"
  - export CC="gcc-7"
  
script: 
  - g++-7 --version
  - ./buildFromDeps.sh
