sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - cmake-data
      - g++-6
      - libgtest-dev
      - valgrind


before_install:
  - ./buildDeps.sh

install:
  - pip install --user cpp-coveralls
  - export CXX="g++-6"
  - export CC="gcc-6"
  
script: 
  - g++-6 --version
  - ./buildFromDeps.sh
